[formatter]
[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
includes = ["*.html", "*.js", "*.json", "*.md", "*.yaml"]
options = ["--write"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-bn", "-ci", "-sr", "-i", "2", "-s", "-w"]
