# [formatter.go]
# command = "gofumpt"
# includes = ["*.go"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

# [formatter.prettier]
# command = "prettier"
# includes = [
#     "*.css",
#     "*.html",
#     "*.js",
#     "*.json",
#     "*.jsx",
#     "*.md",
#     "*.mdx",
#     "*.scss",
#     "*.ts",
#     "*.yaml",
# ]
# options = ["--write"]


# [formatter.python]
# command = "black"
# includes = ["*.py"]

# [formatter.rust]
# command = "rustfmt"
# includes = ["*.rs"]

# [formatter.shell]
# command = "shfmt"
# includes = ["*.sh", "*.bash", "*.zsh"]
# options = [
#     "--binary-next-line",
#     "--case-indent",
#     "--func-next-line",
#     "--space-redirects",
#     "--indent",
#     "2",
#     "--simplify",
#     "--write",
# ]
